services:
  - type: web
    name: phishing-detector-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
